version: '3.7'

services:
  
  consul-server1:
    image: hashicorp/consul:1.14
    restart: always
    networks:
      - colax-server-net
    expose:
      - "8300"
      - "8301/tcp"
      - "8301/udp"
      - "8302/tcp"
      - "8302/udp"
      - "8500"
      - "8600/tcp"
      - "8600/udp"
    command: "agent -server -bootstrap-expect=1 -node=server1 -bind=0.0.0.0 -client=0.0.0.0"

  consul-client:
    image: hashicorp/consul:1.14
    restart: always
    networks:
      - colax-server-net
    ports:
      - "8500:8500"
    command: "agent -node=client -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul-server1"

  colax-server:
    image: colax-server:latest
    build: .
    environment:
      COLAX_CONSUL_HOST: consul-client
    networks:
      - colax-server-net
    ports:
      - "6733:8000"

networks:
  colax-server-net:
    name: colax-server
